<?php
$modules_rights=array("about"=>array("read"=>"Read",
                                     "write"=>"Write",   
                                    ),
                      "suggestion"=>array("read"=>"Read",
                                     "write"=>"Write",   
                                    ),
                       "stats"=>array("read"=>"Read",
                                     "write"=>"Write",   
                                    ),  
                       "regions"=>array("read"=>"Read",
                                     "write"=>"Write",   
                                    ),
                        "polls"=>array("read"=>"Read",
                                     "write"=>"Write",   
                                    ),  
                         "peopleprofile"=>array("read"=>"Read",
                                     "write"=>"Write",   
                                    ),
                        "mliststats"=>array("read"=>"Read",
                                     "write"=>"Write",   
                                    ),
                       "message"=>array("read"=>"Read",
                                     "write"=>"Write",   
                                    ),  
                       "memlist"=>array("read"=>"Read",
                                     "write"=>"Write",   
                                    ),
                        "masterlist"=>array("read"=>"Read",
                                     "write"=>"Write",   
                                    ),  
                         "emailtemplate"=>array("read"=>"Read",
                                     "write"=>"Write",   
                                    ),
                       "emails"=>array("read"=>"Read",
                                     "write"=>"Write",   
                                    ),
                       "dashboard"=>array("read"=>"Read",
                                     "write"=>"Write",
                                     "taskread"=>"Task Read",  
                                     "taskwrite"=>"Task Write",
                                     "gtaskread"=>"Give Task Read",  
                                     "gtaskwrite"=>"Give Task Write",     
                                    ),  
                       "calendar"=>array("read"=>"Read",
                                     "write"=>"Write",   
                                    ),
                        "banner"=>array("read"=>"Read",
                                     "write"=>"Write",   
                                    ),  
                         "affilateright"=>array("read"=>"Read",
                                     "write"=>"Write",   
                                    ),
                        "ads"=>array("read"=>"Read",
                                     "write"=>"Write",   
                                    ),
                        "affilate"=>array("read"=>"Read",
                                     "write"=>"Write",   
                                    ) 
                        ,
                        "catmasterlist"=>array("read"=>"Read",
                                     "write"=>"Write",   
                                    )             
                                                                                                                                                                     

                    ); // end Array
//suggestion  stats regions  polls  peopleprofile mliststats  message memlist  masterlist  emailtemplate emails  dashboard  calendar  banner affilateright
?>